server:
  port: ${CRUD_PORT:8080}

environment:
  servers:
    FRS_CORE:
      url: ${CORE_URL:http://dev.frs.exadel.by:8082}

app:
  security:
    oauth2:
      clients:
        COMMON:
          access-token-validity: ${COMMON_ACCESS_TOKEN_VALIDITY:2400}
          authorities: ROLE_APP_LOGIN
          authorized-grant-types: password,refresh_token
          client-id: CommonClientId
          client-scope: all
          client-secret: password
          refresh-token-validity: ${COMMON_REFRESH_TOKEN_VALIDITY:1209600}
          resource-ids: authorization

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/frs}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc.lob.non_contextual_creation: true # fix for Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
    open-in-view: true
    generate-ddl: false
  mail:
    sender: ${FRS_EMAIL:frs@msqv500.exadel.by}
    host: ${POSTFIX_HOST:msqv500.exadel.by}
    port: 25
    test-connection: false
    properties.mail:
      debug: true
      smtp:
        connectiontimeout: 12000
        writetimeout: 12000
        starttls:
          enable: true
        ssl:
          trust: ${POSTFIX_HOST}

security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  expire-length: 86400000

proxy:
  baseUrl: ${PROXY_URL:http://localhost:5000}

swagger:
  auth:
    server: http://localhost:${server.port}
  info:
    title: Face Recognition Service - Client
    version: 0.0.2-SNAPSHOT

host:
  frs: ${FRS_CRUD_HOST:dev.frs.exadel.by}
  full:
    dns:
      auth:
        link: ${DNS_URL:http://localhost:${server.port}}

logging:
  level:
    web: DEBUG
    org.springframework.web: DEBUG
    com:
      exadel:
        frs: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

registration:
  token:
    expires: 3600000
    scheduler:
      period: 300000

image:
  types:
    - tif
    - tiff
    - jpg
    - jpeg
    - png
    - bmp
    - ico
    - gif
    - webp